### PR TITLE
Picovoice Flutter SDK: Add manual wake

### PR DESCRIPTION
**Pull request by AlexHartford**
Fixes https://github.com/Picovoice/picovoice/issues/106

### CODE REVIEW

**Comment by laves** [comment]
@AlexHartford, we are going to hold on merging this in until we can add this to the API for all of our Picovoice SDKs. Until then, you can still achieve the same functionality using flutter-voice-processor, porcupine and rhino in a custom arrangement.

**Comment by AlexHartford** [comment]
Sounds good, Flutter makes it simple to use forked packages so take your time!

**Comment by laves** [comment]
We decided not to include this feature in the most recent release since the same functionality can be achieved by combining Porcupine and Rhino in a manual configuration. Appreciate the input!

**Comment by AlexHartford** [comment]
It could be helpful to future readers if you included the strategy for accomplishing this behavior.

**Pull request closed without merging**
