### PR TITLE
Flutter SDK (Picovoice): Add Analysis options

### PR DESCRIPTION
**Pull request by AlexHartford**
Added analysis options that enforce dart best practices which should be followed in publicly available APIs. No functionality is impacted by this change.

### CODE REVIEW

**Comment by AlexHartford** [comment]
Also should note I didn't fix every analysis issue, but now an IDE should have warnings where they could be fixed or ignored.

**Comment by laves** [comment]
@AlexHartford, what tool generated these changes and it is a Flutter standard? We're reluctant to merge in a PR with so many modifications without knowing more about the tool that generated them. When I run `flutter analyze` on our SDK, no warnings are reported.

**Comment by AlexHartford** [comment]
https://dart.dev/guides/language/analysis-options

The reason flutter analyze doesn't have warnings is because you haven't configured it to find any besides the most basic "it will run" type lints.

The analysis options file I added is one I've seen that's generally accepted for public packages. However, if you don't want to take my word for it, try https://pub.dev/packages/flutter_lints instead, as I believe this is the most up-to-date way of handling this.

This would really benefit this package as having functions exported with dynamic types makes using the API difficult.

**Comment by laves** [comment]
Great, okay, we've decided we'll add this stricter linting to our Flutter APIs. As with the other API change you've proposed, we'll have to wait until we can spend the cycles to update all of our Flutter packages, but we will make the update. Until then, we'll put this PR on hold. Thanks @AlexHartford, we appreciate your insight.

**Comment by AlexHartford** [comment]
You're welcome! I'm a (new) big fan of Picovoice, hope to do some cool stuff with it.

**Comment by laves** [comment]
@AlexHartford - we added analysis options in v2.0. Appreciate the suggestion there.

**Pull request closed without merging**
